##
## 当 pr merge 到 master 时触发
##

name: ci

on: 
  push:
    branches-ignore:
      - 'master'
    paths:
      - '**.cc'
      - '**.c'
      - '**.h'
      - '**.hpp'
      - 'CMakeLists.txt'

jobs:
  build:
    name: build-lib
    runs-on: ubuntu-latest
    steps:
      - name: step1 checkout
        uses: actions/checkout@v1
    steps:
      - name: step2 dosomething
        shell: bash
        run: |
          echo "当前所处路径:"
          pwd
          ls -al