##
## 当 pr merge 到 master 时触发
##

name: ci

on: 
  push:
    branches:
      - 'master'
    paths:
      - 'yrpc/**'
      - 'example/**'
      - 'CMakeLists.txt'
  pull_request:
    branches:
      - 'master'


jobs:
  build:
    name: 项目构建
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: step2 dosomething
        shell: bash
        run: |
          cd shell
          ./test.sh