##
## 当 pr merge 到 master 时触发
##

name: ci

on: 
  push:
    branches:
      - 'master'
    paths:
      - '**.cc'
      - '**.c'
      - '**.h'
      - '**.hpp'
      - 'CMakeLists.txt'
  pull_request:
    branches:
      - 'master'


jobs:
  build:
    name: build-lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: step2 dosomething
        shell: bash
        run: |
          echo "当前所处路径:"
          echo ${{github.workspace}}
          echo %PATH%
          pwd
          ls -al
  test:
    name: 单元测试
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: do test
        shell: bash
        run: |
          cd ${{github.workspace}}/shell
          ./build.sh
          ./test.sh